name: Petclinic CI/CD

on:
  repository_dispatch:
    types:
      - app-commit

permissions:
  contents: read

jobs:

  # ============================================================
  # 1. Detect which services changed
  # ============================================================
  detect-changes:
    name: Detect changed services
    runs-on: ubuntu-latest

    outputs:
      customers: ${{ steps.changes.outputs.customers }}
      vets: ${{ steps.changes.outputs.vets }}
      visits: ${{ steps.changes.outputs.visits }}
      frontend: ${{ steps.changes.outputs.frontend }}
      all: ${{ steps.changes.outputs.all }}

    steps:

      - name: Checkout application
        uses: actions/checkout@v4
        with:
          repository: AyoubRhatous/petclinic-microservices
          ref: ${{ github.event.client_payload.sha }}
          fetch-depth: 0

      - name: Detect changes
        id: changes
        shell: bash
        run: |

          SHA="${{ github.event.client_payload.sha }}"

          echo "Analyzing commit: $SHA"

          CHANGED_FILES=$(git diff-tree \
            --no-commit-id \
            --name-only \
            -r \
            "$SHA")

          echo "Changed files:"
          echo "$CHANGED_FILES"

          CUSTOMERS=false
          VETS=false
          VISITS=false
          FRONTEND=false
          ALL=false

          # Root Maven configuration changed
          if echo "$CHANGED_FILES" | grep -qE '^(pom.xml|.mvn/|mvnw|mvnw.cmd)'; then
            ALL=true
          fi

          # Customers
          if echo "$CHANGED_FILES" | grep -q '^petclinic-customers-service/'; then
            CUSTOMERS=true
          fi

          # Vets
          if echo "$CHANGED_FILES" | grep -q '^petclinic-vets-service/'; then
            VETS=true
          fi

          # Visits
          if echo "$CHANGED_FILES" | grep -q '^petclinic-visits-service/'; then
            VISITS=true
          fi

          # Frontend
          if echo "$CHANGED_FILES" | grep -q '^petclinic-frontend/'; then
            FRONTEND=true
          fi

          echo "customers=$CUSTOMERS" >> "$GITHUB_OUTPUT"
          echo "vets=$VETS" >> "$GITHUB_OUTPUT"
          echo "visits=$VISITS" >> "$GITHUB_OUTPUT"
          echo "frontend=$FRONTEND" >> "$GITHUB_OUTPUT"
          echo "all=$ALL" >> "$GITHUB_OUTPUT"


  # ============================================================
  # 2. Build Customers
  # ============================================================
  build-customers:
    name: Build Customers Service
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.customers == 'true' ||
      needs.detect-changes.outputs.all == 'true'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout application
        uses: actions/checkout@v4
        with:
          repository: AyoubRhatous/petclinic-microservices
          ref: ${{ github.event.client_payload.sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Customers Service
        run: |
          mvn -pl petclinic-customers-service -am clean verify
      # -------------------------------------------------------- # 4. SonarQube Cloud - SAST / Code Quality # -------------------------------------------------------- 
      - name: SonarQube analysis 
        continue-on-error: true 
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: https://sonarcloud.io 
        run: |
          mvn \
            org.sonarsource.scanner.maven:sonar-maven-plugin:5.8.0.7211:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN

      # --------------------------------------------------------
      # Trivy - Filesystem Security Scan
      # --------------------------------------------------------
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.35.0
        continue-on-error: true
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,secret,misconfig
          severity: HIGH,CRITICAL
          exit-code: '0'
          format: table
          
      # --------------------------------------------------------
      # Docker - Build Customers Image
      # --------------------------------------------------------
      - name: Build Customers Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.event.client_payload.sha }}
        run: |
          docker build \
            -t "$DOCKERHUB_USERNAME/petclinic-customers:$IMAGE_TAG" \
            ./petclinic-customers-service

      # --------------------------------------------------------
      # Trivy - Container Image Security Scan
      # --------------------------------------------------------
      - name: Trivy container image scan
        uses: aquasecurity/trivy-action@v0.35.0
        continue-on-error: true
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.event.client_payload.sha }}
        with:
          image-ref: '${{ env.DOCKERHUB_USERNAME }}/petclinic-customers:${{ env.IMAGE_TAG }}'
          scanners: vuln,secret
          severity: HIGH,CRITICAL
          exit-code: '0'
          format: table
      # --------------------------------------------------------
      # Trivy - Generate SBOM
      # --------------------------------------------------------
      - name: Generate Customers SBOM
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.event.client_payload.sha }}
        run: |
          mkdir -p sbom

          trivy image \
            --format cyclonedx \
            --output sbom/customers-${IMAGE_TAG}.cdx.json \
            "$DOCKERHUB_USERNAME/petclinic-customers:$IMAGE_TAG"
      # --------------------------------------------------------
      # Publish SBOM to Security Repository
      # --------------------------------------------------------
      - name: Publish Customers SBOM
        env:
          GH_TOKEN: ${{ secrets.SECURITY_REPO_TOKEN }}
          IMAGE_TAG: ${{ github.event.client_payload.sha }}
        run: |
          git clone \
            https://x-access-token:${GH_TOKEN}@github.com/AyoubRhatous/security-repo-sbom.git \
            security-repo

          mkdir -p "security-repo/sbom/customers"

          cp \
            "sbom/customers-${IMAGE_TAG}.cdx.json" \
            "security-repo/sbom/customers/${IMAGE_TAG}.cdx.json"

          cd security-repo

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add sbom/customers/

          git commit \
            -m "chore(sbom): customers ${IMAGE_TAG}" \
            || echo "No changes to commit"

          git push
      # --------------------------------------------------------
      # Docker Hub - Login
      # --------------------------------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --------------------------------------------------------
      # Docker Hub - Push Customers Image
      # --------------------------------------------------------
      - name: Push Customers Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.event.client_payload.sha }}
        run: |
          docker push \
            "$DOCKERHUB_USERNAME/petclinic-customers:$IMAGE_TAG"

  # ============================================================
  # 3. Build Vets
  # ============================================================
  build-vets:
    name: Build Vets Service
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.vets == 'true' ||
      needs.detect-changes.outputs.all == 'true'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout application
        uses: actions/checkout@v4
        with:
          repository: AyoubRhatous/petclinic-microservices
          ref: ${{ github.event.client_payload.sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Vets Service
        run: |
          ./mvnw -pl petclinic-vets-service -am clean verify
      # -------------------------------------------------------- # 4. SonarQube Cloud - SAST / Code Quality # -------------------------------------------------------- 
      - name: SonarQube analysis 
        continue-on-error: true 
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: https://sonarcloud.io 
        run: |
          mvn \
            org.sonarsource.scanner.maven:sonar-maven-plugin:5.8.0.7211:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN

      # --------------------------------------------------------
      # Trivy - Filesystem Security Scan
      # --------------------------------------------------------
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.35.0
        continue-on-error: true
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,secret,misconfig
          severity: HIGH,CRITICAL
          exit-code: '0'
          format: table
          
      # --------------------------------------------------------
      # Docker - Build  Vets Image
      # --------------------------------------------------------
      - name: Build Vets Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.event.client_payload.sha }}
        run: |
          docker build \
            -t "$DOCKERHUB_USERNAME/petclinic-vets:$IMAGE_TAG" \
            ./petclinic-vets-service

      # --------------------------------------------------------
      # Trivy - Container Image Security Scan
      # --------------------------------------------------------
      - name: Trivy container image scan
        uses: aquasecurity/trivy-action@v0.35.0
        continue-on-error: true
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.event.client_payload.sha }}
        with:
          image-ref: '${{ env.DOCKERHUB_USERNAME }}/petclinic-vets:${{ env.IMAGE_TAG }}'
          scanners: vuln,secret
          severity: HIGH,CRITICAL
          exit-code: '0'
          format: table
      # --------------------------------------------------------
      # Trivy - Generate SBOM
      # --------------------------------------------------------
      - name: Generate Vets SBOM
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.event.client_payload.sha }}
        run: |
          mkdir -p sbom

          trivy image \
            --format cyclonedx \
            --output sbom/vets-${IMAGE_TAG}.cdx.json \
            "$DOCKERHUB_USERNAME/petclinic-vets:$IMAGE_TAG"
      # --------------------------------------------------------
      # Publish SBOM to Security Repository
      # --------------------------------------------------------
      - name: Publish Vets SBOM
        env:
          GH_TOKEN: ${{ secrets.SECURITY_REPO_TOKEN }}
          IMAGE_TAG: ${{ github.event.client_payload.sha }}
        run: |
          git clone \
            https://x-access-token:${GH_TOKEN}@github.com/AyoubRhatous/security-repo-sbom.git \
            security-repo

          mkdir -p "security-repo/sbom/vets"

          cp \
            "sbom/vets-${IMAGE_TAG}.cdx.json" \
            "security-repo/sbom/vets/${IMAGE_TAG}.cdx.json"

          cd security-repo

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add sbom/vets/

          git commit \
            -m "chore(sbom): customers ${IMAGE_TAG}" \
            || echo "No changes to commit"

          git push
      # --------------------------------------------------------
      # Docker Hub - Login
      # --------------------------------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --------------------------------------------------------
      # Docker Hub - Push Vets Image
      # --------------------------------------------------------
      - name: Push Vets Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.event.client_payload.sha }}
        run: |
          docker push \
            "$DOCKERHUB_USERNAME/petclinic-vets:$IMAGE_TAG"

  # ============================================================
  # 4. Build Visits
  # ============================================================
  build-visits:
    name: Build Visits Service
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.visits == 'true' ||
      needs.detect-changes.outputs.all == 'true'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout application
        uses: actions/checkout@v4
        with:
          repository: AyoubRhatous/petclinic-microservices
          ref: ${{ github.event.client_payload.sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Visits Service
        run: |
          ./mvnw -pl petclinic-visits-service -am clean verify


  # ============================================================
  # 5. Build Frontend
  # ============================================================
  build-frontend:
    name: Build Frontend
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.frontend == 'true' ||
      needs.detect-changes.outputs.all == 'true'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout application
        uses: actions/checkout@v4
        with:
          repository: AyoubRhatous/petclinic-microservices
          ref: ${{ github.event.client_payload.sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Frontend
        run: |
          ./mvnw -pl petclinic-frontend -am clean verify
