name: Petclinic CI/CD

on:
  repository_dispatch:
    types:
      - app-commit

permissions:
  contents: read

jobs:

  detect-changes:
    name: Detect changed services
    runs-on: ubuntu-latest

    steps:

      - name: Checkout application
        uses: actions/checkout@v4
        with:
          repository: AyoubRhatous/petclinic-microservices
          ref: ${{ github.event.client_payload.sha }}
          fetch-depth: 0

      - name: Detect changed files
        run: |
          echo "Commit:"
          echo "${{ github.event.client_payload.sha }}"

          echo ""
          echo "Changed files:"
          git diff-tree --no-commit-id --name-only -r \
            "${{ github.event.client_payload.sha }}"
